language: node_js
node_js:
  - node
dist: trusty
install: yarn install
notifications:
  email: false
sudo: false
cache: yarn
script:
  - yarn test:coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
