name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Run with Node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Versions
        run: |
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"
      - run: npm ci
      - run: npm test